
version: '3.7'
services:
  nginx:
    build: ./docker
    container_name: server_container
    working_dir: '/var/www/html'
    ports:
      - 9001:80
    networks:
      - laravel-network   
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx-log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf

networks:
  laravel-network:
    driver: bridge